language: python
sudo: required
python:
  - "3.6"
install:
  - pip install black flake8 mypy
script:
  - python test.py --only-static

cache:
  pip: true
  yarn: true
  directories:
    - node_modules